# Site settings
title: NoCoNewsHackers
email: noconewshackers@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  NoCoNewsHackers is a small group of students, journalists and software
  developers who share ideas and skills related to storytelling in the 
  digital age.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: noconewshackers
github_username:  ncnh

# Build settings
markdown: kramdown
